name: Deploy.Ec2

on:
  workflow_dispatch:

jobs:
  deploy-application:
    name: Deploy.Ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Connect to EC2 Instance and Update Changes
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/banking-app/
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master
