name: Deploy.Backend

on:
    workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy.Backend.Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Connect to EC2 and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          cd /home/ubuntu/banking-app/banking &&
          npm ci &&
          sudo pm2 stop index.js &&
          sudo pm2 start index.js

